IMG_HEIGHT = 12
IMG_WIDTH = 12
INPUT_DIM = IMG_HEIGHT * IMG_WIDTH
NUM_CLASSES = 5
TARGET_DIGITS = (0, 1, 2, 3, 4)
TRAIN_SIZE = 1200
TEST_SIZE = 300

PROJ_DIM = 10
PROJ_MODE = "random"
HIDDEN_DIM = 4
OUTPUT_DIM = NUM_CLASSES
ACTIVATION = "softmax"

CARLEMAN_N = 2
POLY_DEGREE = 3

TIME_STEP = 0.1
EPOCHS = 10
TOTAL_STEPS = 120000
RELINEARIZE_INTERVAL = 5

QRT_LEARNING_RATE = 0.1
QRT_GRAD_CLIP = 2.0
QRT_WEIGHT_DECAY = 0.0

EPSILON = 0.025
EPSILON_TRAIN = 0.025
ATTACK_STEP_SIZE = 0.01
ATTACK_STEPS = 10

SOLVER_DIAGNOSTICS = False
LINEAR_SOLVER_BACKEND = "hhl_research"
LINEAR_SOLVER_MAX_DENSE_DIM = 700000
STRICT_HHL = False

QRT_OBJECTIVE_MODE = "batch_perturbation"
QRT_BATCH_SIZE = 5
QRT_BATCH_SIZES = (5,)
QRT_W_DIM_MODE = "per_sample"
QRT_DISABLE_W_PHASE = False
QRT_STRICT_V12_ALTERNATION = True
QRT_ADVERSARY_FIRST = True
QRT_ADVERSARY_STEP_SIZE = 0.1
QRT_STATE_COORDINATES = "delta"

CLASSICAL_BATCH_SIZE = 5
EVAL_BATCH_SIZE = 100
USE_COMBINED_LOSS = False
LOSS_ALPHA = 0.5

HHL_PRECISION = 1e-6
HHL_ACCEPTANCE_REL_RESIDUAL = 0.25
NOISE_SCALE = 0.0
NOISE_KAPPA_CAP = 1e3
RANDOM_SEED = 42
QRT_EVAL_INTERVAL = 5

F2_MODE = "full"
F2_FULL_DIM_LIMIT = 800
F2_EPS = 1e-3
F2_APPROX_LEVEL = 0.0
F2_TOP_CROSS = 0

EXTRACT_F3 = False
F3_EPS = 3e-3
F3_USE_FLOAT64 = True
